[General]
#################### General ####################
# Variante LeyzS/pywal: fondo arch-main + paleta teal (#437E81) sobre #181818

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding="0"

Font="JetBrainsMono Nerd Font"
FontSize="12"
KeyboardSize="0.4"
RoundCorners="20"

Locale="es_ES"
HourFormat="HH:mm"
DateFormat="dddd, dd MMM"

HeaderText=""

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/arch-teal.png"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.3"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

HeaderTextColor="#c5c5c5"
DateTextColor="#458689"
TimeTextColor="#c5c5c5"

FormBackgroundColor="#181818"
BackgroundColor="#181818"
DimBackgroundColor="#181818"

LoginFieldBackgroundColor="#2F3F40"
PasswordFieldBackgroundColor="#2F3F40"
LoginFieldTextColor="#c5c5c5"
PasswordFieldTextColor="#c5c5c5"
UserIconColor="#437E81"
PasswordIconColor="#437E81"

PlaceholderTextColor="#8a9a9b"
WarningColor="#cc6666"

LoginButtonTextColor="#181818"
LoginButtonBackgroundColor="#437E81"
SystemButtonsIconsColor="#437E81"
SessionButtonTextColor="#437E81"
VirtualKeyboardButtonTextColor="#437E81"

DropdownTextColor="#181818"
DropdownSelectedBackgroundColor="#458689"
DropdownBackgroundColor="#437E81"

HighlightTextColor="#181818"
HighlightBackgroundColor="#458689"
HighlightBorderColor="#458689"

HoverUserIconColor="#458689"
HoverPasswordIconColor="#458689"
HoverSystemButtonsIconsColor="#458689"
HoverSessionButtonTextColor="#458689"
HoverVirtualKeyboardButtonTextColor="#458689"

#################### Form ####################

PartialBlur="true"
FullBlur="false"
BlurMax="32"
Blur="1.0"

HaveFormBackground="true"
FormPosition="center"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="true"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="true"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername="Usuario"
TranslatePlaceholderPassword="Contraseña"
TranslateLogin="Entrar"
TranslateLoginFailedWarning="Contraseña incorrecta"
TranslateCapslockWarning="Mayúsculas activadas"
TranslateSuspend="Suspender"
TranslateHibernate="Hibernar"
TranslateReboot="Reiniciar"
TranslateShutdown="Apagar"
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
