#!/bin/sh
# =============================================================
# Script Name: MonitorSetup
# Description: Dynamic multi-monitor configuration for bspwm using xrandr
# Features:
#   - Auto-detect connected monitors (Up to 4 monitors)
#   - Dynamic workspace assignment
#   - Resolution/refresh rate detection
#   - ADAPTABLE: monitors are ordered by physical X position
#     (leftmost = monitor_1 = desktops 1-5, rightmost = monitor_2 = 6-10)
#
# Author: gh0stzk (adapted by runer)
# Date:   24.04.2025
#
# Copyright (C) 2021-2026 gh0stzk <z0mbi3.zk@protonmail.com>
# Licensed under GPL-3.0 license
# =============================================================

# xrandr cmd
XRANDR_OUTPUT=$(xrandr)

# Remove disconnected monmitors
xrandr | while read -r mon state _; do
    [ "$state" = "disconnected" ] && xrandr --output "$mon" --off
done

# Function to obtain monitor info (POSIX-compliant)
get_monitor_info() {
    echo "$XRANDR_OUTPUT" | awk -v monitor="$1" '
        $1 == monitor { getline; print $1, $2 }
    ' | tr -d '*+'
}

# Get connected monitors ORDERED BY PHYSICAL X POSITION (leftmost first).
# This makes the script ADAPTABLE: no matter which monitor is plugged in
# first, the leftmost one always gets the 1-5 range and the rightmost 6-10.
set -- $(xrandr --query | awk '
    $1 ~ /^[A-Z]/ && / connected/ {
        if (match($0, /[0-9]+x[0-9]+[+-](-?[0-9]+)[+-](-?[0-9]+)/, m)) {
            x = m[1] + 0
            print x, $1
        }
    }' | sort -n | awk '{print $2}')

NUM_MONITORS=$#

# Main case for monitor configuration
case $NUM_MONITORS in
    1)
        monitor_1="$1"
        set -- $(get_monitor_info "$monitor_1")
        mode_1="$1"
        rate_1="$2"

        xrandr --output "$monitor_1" --primary --mode "$mode_1" --pos 0x0 --auto --rate "$rate_1"
        bspc monitor "$monitor_1" -d 1 2 3 4 5 6 7 8 9 10
        bspc wm -O "$monitor_1"
        ;;

    2)
        monitor_1="$1"
        monitor_2="$2"

        set -- $(get_monitor_info "$monitor_1")
        mode_1="$1"
        rate_1="$2"

        set -- $(get_monitor_info "$monitor_2")
        mode_2="$1"
        rate_2="$2"

        xrandr --output "$monitor_1" --primary --mode "$mode_1" --pos 0x0 --auto --rate "$rate_1" \
               --output "$monitor_2" --mode "$mode_2" --right-of "$monitor_1" --auto --rate "$rate_2"

        bspc monitor "$monitor_1" -d 1 2 3 4 5
        bspc monitor "$monitor_2" -d 6 7 8 9 10
        bspc wm -O "$monitor_1" "$monitor_2"
        ;;

    3)
        monitor_1="$1"
        monitor_2="$2"
        monitor_3="$3"

        set -- $(get_monitor_info "$monitor_1")
        mode_1="$1"
        rate_1="$2"

        set -- $(get_monitor_info "$monitor_2")
        mode_2="$1"
        rate_2="$2"

        set -- $(get_monitor_info "$monitor_3")
        mode_3="$1"
        rate_3="$2"

        xrandr --output "$monitor_1" --primary --mode "$mode_1" --pos 0x0 --auto --rate "$rate_1" \
               --output "$monitor_2" --mode "$mode_2" --left-of "$monitor_1" --auto --rate "$rate_2" \
               --output "$monitor_3" --mode "$mode_3" --right-of "$monitor_1" --auto --rate "$rate_3"

        bspc monitor "$monitor_1" -d 1 2 3 4 5
        bspc monitor "$monitor_2" -d 6 7 8 9 10
        bspc monitor "$monitor_3" -d 11 12 13 14 15
        bspc wm -O "$monitor_1" "$monitor_2" "$monitor_3"
        ;;

    4)
        monitor_1="$1"
        monitor_2="$2"
        monitor_3="$3"
        monitor_4="$4"

        set -- $(get_monitor_info "$monitor_1")
        mode_1="$1"
        rate_1="$2"

        set -- $(get_monitor_info "$monitor_2")
        mode_2="$1"
        rate_2="$2"

        set -- $(get_monitor_info "$monitor_3")
        mode_3="$1"
        rate_3="$2"

        set -- $(get_monitor_info "$monitor_4")
        mode_4="$1"
        rate_4="$2"

        xrandr --output "$monitor_1" --primary --mode "$mode_1" --pos 0x0 --auto --rate "$rate_1" \
               --output "$monitor_2" --mode "$mode_2" --left-of "$monitor_1" --auto --rate "$rate_2" \
               --output "$monitor_3" --mode "$mode_3" --right-of "$monitor_1" --auto --rate "$rate_3" \
               --output "$monitor_4" --mode "$mode_4" --above "$monitor_1" --auto --rate "$rate_4"

        bspc monitor "$monitor_1" -d 1 2 3 4 5
        bspc monitor "$monitor_2" -d 6 7 8 9 10
        bspc monitor "$monitor_3" -d 11 12 13 14 15
        bspc monitor "$monitor_4" -d 16 17 18 19 20
        bspc wm -O "$monitor_1" "$monitor_2" "$monitor_3" "$monitor_4"
        ;;

    *)
        echo "Warning: Configuration not supported for more than 4 monitors"
        ;;
esac
